name: package
run-name: Package and create release
on: push
jobs:
  build:
    name: Build on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config: [{ name: windows, os: windows-latest, ext: .exe }, { name: linux, os: ubuntu-latest, ext: '' }]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -U pyinstaller
      - name: Package via pyinstaller & compress to gzipped tarball
        run: |
          pyinstaller main.spec
          mv dist/main/main${{ matrix.config.ext }} dist/main/'Not so Dead Cells'${{ matrix.config.ext }}
          tar -czf ${{ matrix.config.name }}.tar.gz -C dist/main .
      - name: Archive packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}
          path: ${{ matrix.config.name }}.tar.gz
  release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: release/*.tar.gz
