name: package
run-name: Package release zips
on: push
jobs:
  build:
    name: Build on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config: [{ name: windows, os: windows-latest, ext: .exe }, { name: linux, os: ubuntu-latest, ext: '' }]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -U pyinstaller
      - name: Package via pyinstaller & compress to gzipped tarball
        run: |
          pyinstaller main.spec
          mv dist/main/main${{ matrix.config.ext }} dist/main/'Not so Dead Cells'${{ matrix.config.ext }}
          tar -czf ${{ matrix.config.name }}.tar.gz -C dist/main .
      - name: Archive packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}
          path: ${{ matrix.config.name }}.tar.gz
  push:
    name: Commit and push to repository
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true
      - name: Commit & push changes
        run: |
          git config --global user.name '2 * r + 2 * t'
          git config --global user.email '61896496+soramanew@users.noreply.github.com'

          git add .
          git commit -m "Auto package"
          git push
